// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class AvailableFeature
    {
        internal static AvailableFeature DeserializeAvailableFeature(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string name = default;
            FeatureState state = default;
            FeatureExtendedState extendedState = default;
            Optional<AdditionalFeatureInfo> additionalInfo = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"u8))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("state"u8))
                {
                    state = property.Value.GetString().ToFeatureState();
                    continue;
                }
                if (property.NameEquals("extendedState"u8))
                {
                    extendedState = property.Value.GetString().ToFeatureExtendedState();
                    continue;
                }
                if (property.NameEquals("additionalInfo"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    additionalInfo = AdditionalFeatureInfo.DeserializeAdditionalFeatureInfo(property.Value);
                    continue;
                }
            }
            return new AvailableFeature(name, state, extendedState, additionalInfo.Value);
        }
    }
}
