// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class ChangeLabelStatus
    {
        internal static ChangeLabelStatus DeserializeChangeLabelStatus(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string id = default;
            Status status = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"u8))
                {
                    id = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("status"u8))
                {
                    status = property.Value.GetString().ToStatus();
                    continue;
                }
            }
            return new ChangeLabelStatus(id, status);
        }
    }
}
