// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatasourceUsage : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("datasourceInstanceId"u8);
            writer.WriteStringValue(DatasourceInstanceId);
            writer.WriteEndObject();
        }

        internal static DatasourceUsage DeserializeDatasourceUsage(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Guid datasourceInstanceId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("datasourceInstanceId"u8))
                {
                    datasourceInstanceId = property.Value.GetGuid();
                    continue;
                }
            }
            return new DatasourceUsage(datasourceInstanceId);
        }
    }
}
