// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatamartBaseProperties
    {
        internal static DatamartBaseProperties DeserializeDatamartBaseProperties(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Guid id = default;
            Optional<string> name = default;
            Optional<string> description = default;
            Optional<DatamartType> type = default;
            Optional<DatamartStatus> status = default;
            Optional<DatamartState> state = default;
            Optional<string> suspendedBatchId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"u8))
                {
                    id = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("name"u8))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("description"u8))
                {
                    description = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    type = property.Value.GetString().ToDatamartType();
                    continue;
                }
                if (property.NameEquals("status"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    status = property.Value.GetString().ToDatamartStatus();
                    continue;
                }
                if (property.NameEquals("state"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    state = property.Value.GetString().ToDatamartState();
                    continue;
                }
                if (property.NameEquals("suspendedBatchId"u8))
                {
                    suspendedBatchId = property.Value.GetString();
                    continue;
                }
            }
            return new DatamartBaseProperties(id, name.Value, description.Value, Optional.ToNullable(type), Optional.ToNullable(status), Optional.ToNullable(state), suspendedBatchId.Value);
        }
    }
}
