// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatasetToDataflowLinkResponse
    {
        internal static DatasetToDataflowLinkResponse DeserializeDatasetToDataflowLinkResponse(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<string> datasetObjectId = default;
            Optional<string> dataflowObjectId = default;
            Optional<string> workspaceObjectId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("datasetObjectId"u8))
                {
                    datasetObjectId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("dataflowObjectId"u8))
                {
                    dataflowObjectId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("workspaceObjectId"u8))
                {
                    workspaceObjectId = property.Value.GetString();
                    continue;
                }
            }
            return new DatasetToDataflowLinkResponse(datasetObjectId.Value, dataflowObjectId.Value, workspaceObjectId.Value);
        }
    }
}
