// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatasetExecuteQueriesResponse
    {
        internal static DatasetExecuteQueriesResponse DeserializeDatasetExecuteQueriesResponse(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<DatasetExecuteQueriesInformationProtectionLabel> informationProtectionLabel = default;
            Optional<IReadOnlyList<DatasetExecuteQueriesQueryResult>> results = default;
            Optional<DatasetExecuteQueriesError> error = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("informationProtectionLabel"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    informationProtectionLabel = DatasetExecuteQueriesInformationProtectionLabel.DeserializeDatasetExecuteQueriesInformationProtectionLabel(property.Value);
                    continue;
                }
                if (property.NameEquals("results"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<DatasetExecuteQueriesQueryResult> array = new List<DatasetExecuteQueriesQueryResult>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DatasetExecuteQueriesQueryResult.DeserializeDatasetExecuteQueriesQueryResult(item));
                    }
                    results = array;
                    continue;
                }
                if (property.NameEquals("error"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    error = DatasetExecuteQueriesError.DeserializeDatasetExecuteQueriesError(property.Value);
                    continue;
                }
            }
            return new DatasetExecuteQueriesResponse(informationProtectionLabel.Value, Optional.ToList(results), error.Value);
        }
    }
}
