// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatamartEndorsmentProperties
    {
        internal static DatamartEndorsmentProperties DeserializeDatamartEndorsmentProperties(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<EndorsementDetails> endorsementDetails = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("endorsementDetails"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    endorsementDetails = EndorsementDetails.DeserializeEndorsementDetails(property.Value);
                    continue;
                }
            }
            return new DatamartEndorsmentProperties(endorsementDetails.Value);
        }
    }
}
