// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A list of miscellaneous properties returned for a dataset. Returned by User and Admin APIs. </summary>
    public partial class DatasetMiscProperties
    {
        /// <summary> Initializes a new instance of <see cref="DatasetMiscProperties"/>. </summary>
        public DatasetMiscProperties()
        {
        }

        /// <summary> Initializes a new instance of <see cref="DatasetMiscProperties"/>. </summary>
        /// <param name="addRowsAPIEnabled"> Whether the dataset allows adding new rows. </param>
        /// <param name="isRefreshable"> Whether the dataset is refreshable or not. A Power BI refreshable dataset is a dataset that has been refreshed at least once, or for which a valid refresh schedule exists. </param>
        /// <param name="isInPlaceSharingEnabled"> Whether the dataset can be shared with external users to be consumed in their own tenant. </param>
        internal DatasetMiscProperties(bool? addRowsAPIEnabled, bool? isRefreshable, bool? isInPlaceSharingEnabled)
        {
            AddRowsAPIEnabled = addRowsAPIEnabled;
            IsRefreshable = isRefreshable;
            IsInPlaceSharingEnabled = isInPlaceSharingEnabled;
        }

        /// <summary> Whether the dataset allows adding new rows. </summary>
        public bool? AddRowsAPIEnabled { get; set; }
        /// <summary> Whether the dataset is refreshable or not. A Power BI refreshable dataset is a dataset that has been refreshed at least once, or for which a valid refresh schedule exists. </summary>
        public bool? IsRefreshable { get; set; }
        /// <summary> Whether the dataset can be shared with external users to be consumed in their own tenant. </summary>
        public bool? IsInPlaceSharingEnabled { get; set; }
    }
}
