// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatasetExecuteQueriesQueryResult
    {
        internal static DatasetExecuteQueriesQueryResult DeserializeDatasetExecuteQueriesQueryResult(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<IReadOnlyList<DatasetExecuteQueriesTableResult>> tables = default;
            Optional<DatasetExecuteQueriesError> error = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("tables"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<DatasetExecuteQueriesTableResult> array = new List<DatasetExecuteQueriesTableResult>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DatasetExecuteQueriesTableResult.DeserializeDatasetExecuteQueriesTableResult(item));
                    }
                    tables = array;
                    continue;
                }
                if (property.NameEquals("error"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    error = DatasetExecuteQueriesError.DeserializeDatasetExecuteQueriesError(property.Value);
                    continue;
                }
            }
            return new DatasetExecuteQueriesQueryResult(Optional.ToList(tables), error.Value);
        }
    }
}
