// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DependentDatamart : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(TargetDatamartId))
            {
                writer.WritePropertyName("targetDatamartId"u8);
                writer.WriteStringValue(TargetDatamartId);
            }
            if (Optional.IsDefined(GroupId))
            {
                writer.WritePropertyName("groupId"u8);
                writer.WriteStringValue(GroupId);
            }
            writer.WriteEndObject();
        }

        internal static DependentDatamart DeserializeDependentDatamart(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<string> targetDatamartId = default;
            Optional<string> groupId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("targetDatamartId"u8))
                {
                    targetDatamartId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("groupId"u8))
                {
                    groupId = property.Value.GetString();
                    continue;
                }
            }
            return new DependentDatamart(targetDatamartId.Value, groupId.Value);
        }
    }
}
