// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DeploymentExecutionPlan
    {
        internal static DeploymentExecutionPlan DeserializeDeploymentExecutionPlan(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<IReadOnlyList<DeploymentExecutionStep>> steps = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("steps"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<DeploymentExecutionStep> array = new List<DeploymentExecutionStep>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DeploymentExecutionStep.DeserializeDeploymentExecutionStep(item));
                    }
                    steps = array;
                    continue;
                }
            }
            return new DeploymentExecutionPlan(Optional.ToList(steps));
        }
    }
}
