// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class Encryption : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(EncryptionStatus))
            {
                writer.WritePropertyName("EncryptionStatus"u8);
                writer.WriteStringValue(EncryptionStatus.Value.ToSerialString());
            }
            writer.WriteEndObject();
        }

        internal static Encryption DeserializeEncryption(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<EncryptionStatus> encryptionStatus = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("EncryptionStatus"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    encryptionStatus = property.Value.GetString().ToEncryptionStatus();
                    continue;
                }
            }
            return new Encryption(Optional.ToNullable(encryptionStatus));
        }
    }
}
