// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A dataset expression. </summary>
    public partial class Expression
    {
        /// <summary> Initializes a new instance of <see cref="Expression"/>. </summary>
        /// <param name="expressionValue"> A dataset table source. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="expressionValue"/> is null. </exception>
        public Expression(ASMashupExpression expressionValue)
        {
            Argument.AssertNotNull(expressionValue, nameof(expressionValue));

            ExpressionValue = expressionValue;
        }

        /// <summary> Initializes a new instance of <see cref="Expression"/>. </summary>
        /// <param name="expressionValue"> A dataset table source. </param>
        /// <param name="name"> The expression name. </param>
        /// <param name="description"> The expression description. </param>
        internal Expression(ASMashupExpression expressionValue, string name, string description)
        {
            ExpressionValue = expressionValue;
            Name = name;
            Description = description;
        }

        /// <summary> A dataset table source. </summary>
        public ASMashupExpression ExpressionValue { get; set; }
        /// <summary> The expression name. </summary>
        public string Name { get; set; }
        /// <summary> The expression description. </summary>
        public string Description { get; set; }
    }
}
