// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GatewayDatasourceCredentialDetails
    {
        internal static GatewayDatasourceCredentialDetails DeserializeGatewayDatasourceCredentialDetails(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<bool> useEndUserOAuth2Credentials = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("useEndUserOAuth2Credentials"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    useEndUserOAuth2Credentials = property.Value.GetBoolean();
                    continue;
                }
            }
            return new GatewayDatasourceCredentialDetails(Optional.ToNullable(useEndUserOAuth2Credentials));
        }
    }
}
