// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GatewayDatasource
    {
        internal static GatewayDatasource DeserializeGatewayDatasource(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Guid id = default;
            Guid gatewayId = default;
            Optional<string> datasourceName = default;
            Optional<string> datasourceType = default;
            Optional<string> connectionDetails = default;
            CredentialType credentialType = default;
            Optional<GatewayDatasourceCredentialDetails> credentialDetails = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"u8))
                {
                    id = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("gatewayId"u8))
                {
                    gatewayId = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("datasourceName"u8))
                {
                    datasourceName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("datasourceType"u8))
                {
                    datasourceType = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("connectionDetails"u8))
                {
                    connectionDetails = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("credentialType"u8))
                {
                    credentialType = property.Value.GetString().ToCredentialType();
                    continue;
                }
                if (property.NameEquals("credentialDetails"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    credentialDetails = GatewayDatasourceCredentialDetails.DeserializeGatewayDatasourceCredentialDetails(property.Value);
                    continue;
                }
            }
            return new GatewayDatasource(id, gatewayId, datasourceName.Value, datasourceType.Value, connectionDetails.Value, credentialType, credentialDetails.Value);
        }
    }
}
