// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GenerateTokenRequestV2 : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsCollectionDefined(Datasets))
            {
                writer.WritePropertyName("datasets"u8);
                writer.WriteStartArray();
                foreach (var item in Datasets)
                {
                    writer.WriteObjectValue<GenerateTokenRequestV2Dataset>(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsCollectionDefined(Reports))
            {
                writer.WritePropertyName("reports"u8);
                writer.WriteStartArray();
                foreach (var item in Reports)
                {
                    writer.WriteObjectValue<GenerateTokenRequestV2Report>(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsCollectionDefined(TargetWorkspaces))
            {
                writer.WritePropertyName("targetWorkspaces"u8);
                writer.WriteStartArray();
                foreach (var item in TargetWorkspaces)
                {
                    writer.WriteObjectValue<GenerateTokenRequestV2TargetWorkspace>(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsCollectionDefined(Identities))
            {
                writer.WritePropertyName("identities"u8);
                writer.WriteStartArray();
                foreach (var item in Identities)
                {
                    writer.WriteObjectValue<EffectiveIdentity>(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsDefined(LifetimeInMinutes))
            {
                writer.WritePropertyName("lifetimeInMinutes"u8);
                writer.WriteNumberValue(LifetimeInMinutes.Value);
            }
            if (Optional.IsCollectionDefined(DatasourceIdentities))
            {
                writer.WritePropertyName("datasourceIdentities"u8);
                writer.WriteStartArray();
                foreach (var item in DatasourceIdentities)
                {
                    writer.WriteObjectValue<DatasourceIdentity>(item);
                }
                writer.WriteEndArray();
            }
            writer.WriteEndObject();
        }

        /// <summary> Convert into a Utf8JsonRequestContent. </summary>
        internal virtual RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue<GenerateTokenRequestV2>(this);
            return content;
        }
    }
}
