// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GoalsRulesRule1OfInt32 : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsCollectionDefined(Conditions))
            {
                writer.WritePropertyName("conditions"u8);
                writer.WriteStartArray();
                foreach (var item in Conditions)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsDefined(Output))
            {
                writer.WritePropertyName("output"u8);
                writer.WriteNumberValue(Output.Value);
            }
            writer.WriteEndObject();
        }

        internal static GoalsRulesRule1OfInt32 DeserializeGoalsRulesRule1OfInt32(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<IList<GoalsRulesRuleCondition>> conditions = default;
            Optional<int> output = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("conditions"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<GoalsRulesRuleCondition> array = new List<GoalsRulesRuleCondition>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(GoalsRulesRuleCondition.DeserializeGoalsRulesRuleCondition(item));
                    }
                    conditions = array;
                    continue;
                }
                if (property.NameEquals("output"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    output = property.Value.GetInt32();
                    continue;
                }
            }
            return new GoalsRulesRule1OfInt32(Optional.ToList(conditions), Optional.ToNullable(output));
        }
    }
}
