// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GoalsRulesRuleValue : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(PercentOf))
            {
                writer.WritePropertyName("percentOf"u8);
                writer.WriteObjectValue(PercentOf);
            }
            if (Optional.IsDefined(Field))
            {
                writer.WritePropertyName("field"u8);
                writer.WriteStringValue(Field);
            }
            if (Optional.IsDefined(DateTime))
            {
                writer.WritePropertyName("dateTime"u8);
                writer.WriteStringValue(DateTime.Value, "O");
            }
            if (Optional.IsDefined(Number))
            {
                writer.WritePropertyName("number"u8);
                writer.WriteNumberValue(Number.Value);
            }
            writer.WriteEndObject();
        }

        internal static GoalsRulesRuleValue DeserializeGoalsRulesRuleValue(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<GoalsRulesPercentOf> percentOf = default;
            Optional<string> field = default;
            Optional<DateTimeOffset> dateTime = default;
            Optional<double> number = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("percentOf"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    percentOf = GoalsRulesPercentOf.DeserializeGoalsRulesPercentOf(property.Value);
                    continue;
                }
                if (property.NameEquals("field"u8))
                {
                    field = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("dateTime"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    dateTime = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("number"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    number = property.Value.GetDouble();
                    continue;
                }
            }
            return new GoalsRulesRuleValue(percentOf.Value, field.Value, Optional.ToNullable(dateTime), Optional.ToNullable(number));
        }
    }
}
