// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GoalsRulesRuleCondition : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(FieldComparison))
            {
                writer.WritePropertyName("fieldComparison"u8);
                writer.WriteObjectValue(FieldComparison);
            }
            if (Optional.IsDefined(Expression))
            {
                writer.WritePropertyName("expression"u8);
                writer.WriteStringValue(Expression);
            }
            writer.WriteEndObject();
        }

        internal static GoalsRulesRuleCondition DeserializeGoalsRulesRuleCondition(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<GoalsRulesFieldComparison> fieldComparison = default;
            Optional<string> expression = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("fieldComparison"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    fieldComparison = GoalsRulesFieldComparison.DeserializeGoalsRulesFieldComparison(property.Value);
                    continue;
                }
                if (property.NameEquals("expression"u8))
                {
                    expression = property.Value.GetString();
                    continue;
                }
            }
            return new GoalsRulesRuleCondition(fieldComparison.Value, expression.Value);
        }
    }
}
