// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class MashupParameter
    {
        internal static MashupParameter DeserializeMashupParameter(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string name = default;
            string type = default;
            Optional<string> currentValue = default;
            bool isRequired = default;
            Optional<IReadOnlyList<string>> suggestedValues = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"u8))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"u8))
                {
                    type = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("currentValue"u8))
                {
                    currentValue = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("isRequired"u8))
                {
                    isRequired = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("suggestedValues"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    suggestedValues = array;
                    continue;
                }
            }
            return new MashupParameter(name, type, currentValue.Value, isRequired, Optional.ToList(suggestedValues));
        }
    }
}
