// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class ModifiedWorkspace
    {
        internal static ModifiedWorkspace DeserializeModifiedWorkspace(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Guid id = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("Id"u8))
                {
                    id = property.Value.GetGuid();
                    continue;
                }
            }
            return new ModifiedWorkspace(id);
        }
    }
}
