// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class PipelineUser : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(AccessRight))
            {
                writer.WritePropertyName("accessRight"u8);
                writer.WriteStringValue(AccessRight.Value.ToString());
            }
            writer.WritePropertyName("identifier"u8);
            writer.WriteStringValue(Identifier);
            writer.WritePropertyName("principalType"u8);
            writer.WriteStringValue(PrincipalType.ToSerialString());
            writer.WriteEndObject();
        }

        internal static PipelineUser DeserializePipelineUser(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<PipelineUserAccessRight> accessRight = default;
            string identifier = default;
            PrincipalType principalType = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("accessRight"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    accessRight = new PipelineUserAccessRight(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("identifier"u8))
                {
                    identifier = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("principalType"u8))
                {
                    principalType = property.Value.GetString().ToPrincipalType();
                    continue;
                }
            }
            return new PipelineUser(identifier, principalType, Optional.ToNullable(accessRight));
        }
    }
}
