// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class PipelineStageDashboard
    {
        internal static PipelineStageDashboard DeserializePipelineStageDashboard(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Guid artifactId = default;
            Optional<string> artifactDisplayName = default;
            Optional<Guid> sourceArtifactId = default;
            Optional<Guid> targetArtifactId = default;
            Optional<DateTimeOffset> lastDeploymentTime = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("artifactId"u8))
                {
                    artifactId = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("artifactDisplayName"u8))
                {
                    artifactDisplayName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("sourceArtifactId"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    sourceArtifactId = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("targetArtifactId"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    targetArtifactId = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("lastDeploymentTime"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    lastDeploymentTime = property.Value.GetDateTimeOffset("O");
                    continue;
                }
            }
            return new PipelineStageDashboard(artifactId, artifactDisplayName.Value, Optional.ToNullable(sourceArtifactId), Optional.ToNullable(targetArtifactId), Optional.ToNullable(lastDeploymentTime));
        }
    }
}
