// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class ReportAuthoringPropertiesById : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(CreatedById))
            {
                writer.WritePropertyName("createdById"u8);
                writer.WriteStringValue(CreatedById);
            }
            if (Optional.IsDefined(ModifiedById))
            {
                writer.WritePropertyName("modifiedById"u8);
                writer.WriteStringValue(ModifiedById);
            }
            writer.WriteEndObject();
        }

        internal static ReportAuthoringPropertiesById DeserializeReportAuthoringPropertiesById(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<string> createdById = default;
            Optional<string> modifiedById = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("createdById"u8))
                {
                    createdById = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("modifiedById"u8))
                {
                    modifiedById = property.Value.GetString();
                    continue;
                }
            }
            return new ReportAuthoringPropertiesById(createdById.Value, modifiedById.Value);
        }
    }
}
