// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class RoleMember : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("memberName"u8);
            writer.WriteStringValue(MemberName);
            if (Optional.IsDefined(MemberId))
            {
                writer.WritePropertyName("memberId"u8);
                writer.WriteStringValue(MemberId);
            }
            if (Optional.IsDefined(MemberType))
            {
                writer.WritePropertyName("memberType"u8);
                writer.WriteStringValue(MemberType);
            }
            if (Optional.IsDefined(IdentityProvider))
            {
                writer.WritePropertyName("identityProvider"u8);
                writer.WriteStringValue(IdentityProvider);
            }
            writer.WriteEndObject();
        }

        internal static RoleMember DeserializeRoleMember(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string memberName = default;
            Optional<string> memberId = default;
            Optional<string> memberType = default;
            Optional<string> identityProvider = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("memberName"u8))
                {
                    memberName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("memberId"u8))
                {
                    memberId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("memberType"u8))
                {
                    memberType = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("identityProvider"u8))
                {
                    identityProvider = property.Value.GetString();
                    continue;
                }
            }
            return new RoleMember(memberName, memberId.Value, memberType.Value, identityProvider.Value);
        }
    }
}
