// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The ID for one of the columns on the scorecard control or scorecard Web UI page. </summary>
    public enum ScorecardColumnId
    {
        /// <summary> Name. </summary>
        Name,
        /// <summary> Owner. </summary>
        Owner,
        /// <summary> Status. </summary>
        Status,
        /// <summary> Value. </summary>
        Value,
        /// <summary> Progress. </summary>
        Progress,
        /// <summary> DueDate. </summary>
        DueDate,
        /// <summary> Notes. </summary>
        Notes
    }
}
