// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class ScorecardColumnSetting : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("columnId"u8);
            writer.WriteStringValue(ColumnId.ToSerialString());
            writer.WritePropertyName("show"u8);
            writer.WriteBooleanValue(Show);
            writer.WriteEndObject();
        }

        internal static ScorecardColumnSetting DeserializeScorecardColumnSetting(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            ScorecardColumnId columnId = default;
            bool show = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("columnId"u8))
                {
                    columnId = property.Value.GetString().ToScorecardColumnId();
                    continue;
                }
                if (property.NameEquals("show"u8))
                {
                    show = property.Value.GetBoolean();
                    continue;
                }
            }
            return new ScorecardColumnSetting(columnId, show);
        }
    }
}
