// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class SensitivityLabel : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("labelId"u8);
            writer.WriteStringValue(LabelId);
            writer.WriteEndObject();
        }

        internal static SensitivityLabel DeserializeSensitivityLabel(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Guid labelId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("labelId"u8))
                {
                    labelId = property.Value.GetGuid();
                    continue;
                }
            }
            return new SensitivityLabel(labelId);
        }
    }
}
