// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class TileEmbedProperties : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(EmbedUrl))
            {
                writer.WritePropertyName("embedUrl"u8);
                writer.WriteStringValue(EmbedUrl);
            }
            if (Optional.IsDefined(EmbedData))
            {
                writer.WritePropertyName("embedData"u8);
                writer.WriteStringValue(EmbedData);
            }
            writer.WriteEndObject();
        }

        internal static TileEmbedProperties DeserializeTileEmbedProperties(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<string> embedUrl = default;
            Optional<string> embedData = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("embedUrl"u8))
                {
                    embedUrl = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("embedData"u8))
                {
                    embedData = property.Value.GetString();
                    continue;
                }
            }
            return new TileEmbedProperties(embedUrl.Value, embedData.Value);
        }
    }
}
