// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class TileLayoutProperties : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(RowSpan))
            {
                writer.WritePropertyName("rowSpan"u8);
                writer.WriteNumberValue(RowSpan.Value);
            }
            if (Optional.IsDefined(ColSpan))
            {
                writer.WritePropertyName("colSpan"u8);
                writer.WriteNumberValue(ColSpan.Value);
            }
            writer.WriteEndObject();
        }

        internal static TileLayoutProperties DeserializeTileLayoutProperties(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            Optional<int> rowSpan = default;
            Optional<int> colSpan = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("rowSpan"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    rowSpan = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("colSpan"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    colSpan = property.Value.GetInt32();
                    continue;
                }
            }
            return new TileLayoutProperties(Optional.ToNullable(rowSpan), Optional.ToNullable(colSpan));
        }
    }
}
