// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class UpdateDatasourceConnectionRequest : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("connectionDetails"u8);
            writer.WriteObjectValue<DatasourceConnectionDetails>(ConnectionDetails);
            if (Optional.IsDefined(DatasourceSelector))
            {
                writer.WritePropertyName("datasourceSelector"u8);
                writer.WriteObjectValue<Datasource>(DatasourceSelector);
            }
            writer.WriteEndObject();
        }

        /// <summary> Convert into a Utf8JsonRequestContent. </summary>
        internal virtual RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue<UpdateDatasourceConnectionRequest>(this);
            return content;
        }
    }
}
