// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.PowerBI.Api.Models;

namespace Microsoft.PowerBI.Api
{
    internal partial class GoalValuesRestClient
    {
        private readonly HttpPipeline _pipeline;
        private readonly Guid _groupId;
        private readonly Guid _scorecardId;
        private readonly Guid _goalId;
        private readonly DateTimeOffset _timestamp;
        private readonly Uri _endpoint;

        /// <summary> The ClientDiagnostics is used to provide tracing support for the client library. </summary>
        internal ClientDiagnostics ClientDiagnostics { get; }

        /// <summary> Initializes a new instance of GoalValuesRestClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="goalId"> The unique identifier of the goal. </param>
        /// <param name="timestamp"> The timestamp for the value of the goal. </param>
        /// <param name="endpoint"> server parameter. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/> or <paramref name="pipeline"/> is null. </exception>
        public GoalValuesRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Guid groupId, Guid scorecardId, Guid goalId, DateTimeOffset timestamp, Uri endpoint = null)
        {
            ClientDiagnostics = clientDiagnostics ?? throw new ArgumentNullException(nameof(clientDiagnostics));
            _pipeline = pipeline ?? throw new ArgumentNullException(nameof(pipeline));
            _groupId = groupId;
            _scorecardId = scorecardId;
            _goalId = goalId;
            _timestamp = timestamp;
            _endpoint = endpoint ?? new Uri("https://api.powerbi.com");
        }

        internal HttpMessage CreatePreviewGetRequest(string expand)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/goalValues", false);
            if (expand != null)
            {
                uri.AppendQuery("$expand", expand, true);
            }
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Reads goal value check-ins. </summary>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `notes`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<GoalValues>> PreviewGetAsync(string expand = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetRequest(expand);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValues value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = GoalValues.DeserializeGoalValues(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Reads goal value check-ins. </summary>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `notes`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<GoalValues> PreviewGet(string expand = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetRequest(expand);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValues value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = GoalValues.DeserializeGoalValues(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewPostRequest(GoalValueCreateRequest goalValue)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/goalValues", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            request.Headers.Add("Content-Type", "application/json");
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue<GoalValueCreateRequest>(goalValue);
            request.Content = content;
            return message;
        }

        /// <summary> Creates a new goal value check-in. </summary>
        /// <param name="goalValue"> Goal value content. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goalValue"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<GoalValue>> PreviewPostAsync(GoalValueCreateRequest goalValue, CancellationToken cancellationToken = default)
        {
            if (goalValue == null)
            {
                throw new ArgumentNullException(nameof(goalValue));
            }

            using var message = CreatePreviewPostRequest(goalValue);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValue value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = GoalValue.DeserializeGoalValue(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Creates a new goal value check-in. </summary>
        /// <param name="goalValue"> Goal value content. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goalValue"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<GoalValue> PreviewPost(GoalValueCreateRequest goalValue, CancellationToken cancellationToken = default)
        {
            if (goalValue == null)
            {
                throw new ArgumentNullException(nameof(goalValue));
            }

            using var message = CreatePreviewPostRequest(goalValue);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValue value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = GoalValue.DeserializeGoalValue(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewGetByIDRequest(string expand)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/goalValues(", false);
            uri.AppendPath(_timestamp, "D", true);
            uri.AppendPath(")", false);
            if (expand != null)
            {
                uri.AppendQuery("$expand", expand, true);
            }
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Reads a goal value check-in by a UTC date timestamp. </summary>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `notes`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<GoalValue>> PreviewGetByIDAsync(string expand = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetByIDRequest(expand);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValue value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = GoalValue.DeserializeGoalValue(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Reads a goal value check-in by a UTC date timestamp. </summary>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `notes`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<GoalValue> PreviewGetByID(string expand = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetByIDRequest(expand);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValue value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = GoalValue.DeserializeGoalValue(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewPatchByIDRequest(GoalValue goalValue)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Patch;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/goalValues(", false);
            uri.AppendPath(_timestamp, "D", true);
            uri.AppendPath(")", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            request.Headers.Add("Content-Type", "application/json");
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue<GoalValue>(goalValue);
            request.Content = content;
            return message;
        }

        /// <summary> Updates a goal value check-in by a UTC date timestamp. </summary>
        /// <param name="goalValue"> The updated content of goal value check-in. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goalValue"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<GoalValue>> PreviewPatchByIDAsync(GoalValue goalValue, CancellationToken cancellationToken = default)
        {
            if (goalValue == null)
            {
                throw new ArgumentNullException(nameof(goalValue));
            }

            using var message = CreatePreviewPatchByIDRequest(goalValue);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValue value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = GoalValue.DeserializeGoalValue(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Updates a goal value check-in by a UTC date timestamp. </summary>
        /// <param name="goalValue"> The updated content of goal value check-in. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goalValue"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<GoalValue> PreviewPatchByID(GoalValue goalValue, CancellationToken cancellationToken = default)
        {
            if (goalValue == null)
            {
                throw new ArgumentNullException(nameof(goalValue));
            }

            using var message = CreatePreviewPatchByIDRequest(goalValue);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalValue value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = GoalValue.DeserializeGoalValue(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewDeleteByIDRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Delete;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/goalValues(", false);
            uri.AppendPath(_timestamp, "D", true);
            uri.AppendPath(")", false);
            request.Uri = uri;
            return message;
        }

        /// <summary> Deletes a goal value check-in by a UTC day timestamp. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response> PreviewDeleteByIDAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteByIDRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 204:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Deletes a goal value check-in by a UTC day timestamp. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response PreviewDeleteByID(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteByIDRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 204:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }
    }
}
