// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.PowerBI.Api.Models;

namespace Microsoft.PowerBI.Api
{
    internal partial class GoalsRestClient
    {
        private readonly HttpPipeline _pipeline;
        private readonly Guid _groupId;
        private readonly Guid _scorecardId;
        private readonly Guid _goalId;
        private readonly Uri _endpoint;

        /// <summary> The ClientDiagnostics is used to provide tracing support for the client library. </summary>
        internal ClientDiagnostics ClientDiagnostics { get; }

        /// <summary> Initializes a new instance of GoalsRestClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="goalId"> The unique identifier of the goal. </param>
        /// <param name="endpoint"> server parameter. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/> or <paramref name="pipeline"/> is null. </exception>
        public GoalsRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Guid groupId, Guid scorecardId, Guid goalId, Uri endpoint = null)
        {
            ClientDiagnostics = clientDiagnostics ?? throw new ArgumentNullException(nameof(clientDiagnostics));
            _pipeline = pipeline ?? throw new ArgumentNullException(nameof(pipeline));
            _groupId = groupId;
            _scorecardId = scorecardId;
            _goalId = goalId;
            _endpoint = endpoint ?? new Uri("https://api.powerbi.com");
        }

        internal HttpMessage CreatePreviewGetRequest(string expand, string select)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals", false);
            if (expand != null)
            {
                uri.AppendQuery("$expand", expand, true);
            }
            if (select != null)
            {
                uri.AppendQuery("$select", select, true);
            }
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Returns a list of goals from a scorecard. </summary>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `goalValues` and `aggregations`. </param>
        /// <param name="select"> Allows the clients to select specific properties from the server. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<Goals>> PreviewGetAsync(string expand = null, string select = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetRequest(expand, select);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goals value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = Goals.DeserializeGoals(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Returns a list of goals from a scorecard. </summary>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `goalValues` and `aggregations`. </param>
        /// <param name="select"> Allows the clients to select specific properties from the server. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<Goals> PreviewGet(string expand = null, string select = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetRequest(expand, select);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goals value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = Goals.DeserializeGoals(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewPostRequest(GoalCreateRequest goal)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            request.Headers.Add("Content-Type", "application/json");
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(goal);
            request.Content = content;
            return message;
        }

        /// <summary> Adds a new goal to a scorecard. </summary>
        /// <param name="goal"> The properties of the new goal. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goal"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<Goal>> PreviewPostAsync(GoalCreateRequest goal, CancellationToken cancellationToken = default)
        {
            if (goal == null)
            {
                throw new ArgumentNullException(nameof(goal));
            }

            using var message = CreatePreviewPostRequest(goal);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Adds a new goal to a scorecard. </summary>
        /// <param name="goal"> The properties of the new goal. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goal"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<Goal> PreviewPost(GoalCreateRequest goal, CancellationToken cancellationToken = default)
        {
            if (goal == null)
            {
                throw new ArgumentNullException(nameof(goal));
            }

            using var message = CreatePreviewPostRequest(goal);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewGetByIDRequest(string expand)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")", false);
            if (expand != null)
            {
                uri.AppendQuery("expand", expand, true);
            }
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Returns a goal by ID from a scorecard. </summary>
        /// <param name="expand"> description. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<Goal>> PreviewGetByIDAsync(string expand = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetByIDRequest(expand);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Returns a goal by ID from a scorecard. </summary>
        /// <param name="expand"> description. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<Goal> PreviewGetByID(string expand = null, CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetByIDRequest(expand);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewPatchByIDRequest(Goal goal)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Patch;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            request.Headers.Add("Content-Type", "application/json");
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(goal);
            request.Content = content;
            return message;
        }

        /// <summary> Updates a goal by ID. </summary>
        /// <param name="goal"> The goal properties to patch. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goal"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<Goal>> PreviewPatchByIDAsync(Goal goal, CancellationToken cancellationToken = default)
        {
            if (goal == null)
            {
                throw new ArgumentNullException(nameof(goal));
            }

            using var message = CreatePreviewPatchByIDRequest(goal);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Updates a goal by ID. </summary>
        /// <param name="goal"> The goal properties to patch. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="goal"/> is null. </exception>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<Goal> PreviewPatchByID(Goal goal, CancellationToken cancellationToken = default)
        {
            if (goal == null)
            {
                throw new ArgumentNullException(nameof(goal));
            }

            using var message = CreatePreviewPatchByIDRequest(goal);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewDeleteByIDRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Delete;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")", false);
            request.Uri = uri;
            return message;
        }

        /// <summary> Deletes a goal from a scorecard by goal ID. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response> PreviewDeleteByIDAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteByIDRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 204:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Deletes a goal from a scorecard by goal ID. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response PreviewDeleteByID(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteByIDRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 204:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewGetRefreshHistoryRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/GetRefreshHistory()", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Reads refresh history of a connected goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<GoalRefreshHistories>> PreviewGetRefreshHistoryAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetRefreshHistoryRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalRefreshHistories value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = GoalRefreshHistories.DeserializeGoalRefreshHistories(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Reads refresh history of a connected goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<GoalRefreshHistories> PreviewGetRefreshHistory(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewGetRefreshHistoryRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        GoalRefreshHistories value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = GoalRefreshHistories.DeserializeGoalRefreshHistories(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewDeleteGoalCurrentValueConnectionRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/DeleteGoalCurrentValueConnection()", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Disconnects the current value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<Goal>> PreviewDeleteGoalCurrentValueConnectionAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteGoalCurrentValueConnectionRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Disconnects the current value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<Goal> PreviewDeleteGoalCurrentValueConnection(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteGoalCurrentValueConnectionRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewDeleteGoalTargetValueConnectionRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/DeleteGoalTargetValueConnection()", false);
            request.Uri = uri;
            request.Headers.Add("Accept", "application/json");
            return message;
        }

        /// <summary> Disconnects the target value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response<Goal>> PreviewDeleteGoalTargetValueConnectionAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteGoalTargetValueConnectionRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Disconnects the target value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response<Goal> PreviewDeleteGoalTargetValueConnection(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewDeleteGoalTargetValueConnectionRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                    {
                        Goal value = default;
                        using var document = JsonDocument.Parse(message.Response.ContentStream);
                        value = Goal.DeserializeGoal(document.RootElement);
                        return Response.FromValue(value, message.Response);
                    }
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewRefreshGoalCurrentValueRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/RefreshGoalCurrentValue()", false);
            request.Uri = uri;
            return message;
        }

        /// <summary> Schedules a refresh of the connected value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response> PreviewRefreshGoalCurrentValueAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewRefreshGoalCurrentValueRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 202:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Schedules a refresh of the connected value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response PreviewRefreshGoalCurrentValue(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewRefreshGoalCurrentValueRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 202:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        internal HttpMessage CreatePreviewRefreshGoalTargetValueRequest()
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/v1.0/myorg/groups/", false);
            uri.AppendPath(_groupId, true);
            uri.AppendPath("/scorecards(", false);
            uri.AppendPath(_scorecardId, true);
            uri.AppendPath(")/goals(", false);
            uri.AppendPath(_goalId, true);
            uri.AppendPath(")/RefreshGoalTargetValue()", false);
            request.Uri = uri;
            return message;
        }

        /// <summary> Schedules a refresh of the target value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public async Task<Response> PreviewRefreshGoalTargetValueAsync(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewRefreshGoalTargetValueRequest();
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 202:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }

        /// <summary> Schedules a refresh of the target value of a goal. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public Response PreviewRefreshGoalTargetValue(CancellationToken cancellationToken = default)
        {
            using var message = CreatePreviewRefreshGoalTargetValueRequest();
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 202:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }
        }
    }
}
